// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Hours() {
  return window['go']['backend']['Backend']['Hours']();
}

export function Minutes() {
  return window['go']['backend']['Backend']['Minutes']();
}

export function SetTimerDuration(arg1, arg2) {
  return window['go']['backend']['Backend']['SetTimerDuration'](arg1, arg2);
}

export function StartTimer() {
  return window['go']['backend']['Backend']['StartTimer']();
}

export function TimerActive() {
  return window['go']['backend']['Backend']['TimerActive']();
}

export function ToggleTimer() {
  return window['go']['backend']['Backend']['ToggleTimer']();
}
