// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Hours():Promise<number>;

export function Minutes():Promise<number>;

export function Seconds():Promise<number>;

export function SetTimerDuration(arg1:number,arg2:number,arg3:number):Promise<void>;

export function StartTimer():Promise<void>;

export function StopTimer():Promise<void>;
