// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Hours() {
  return window['go']['backend']['Backend']['Hours']();
}

export function Minutes() {
  return window['go']['backend']['Backend']['Minutes']();
}

export function RestartTimer() {
  return window['go']['backend']['Backend']['RestartTimer']();
}

export function SetHours(arg1) {
  return window['go']['backend']['Backend']['SetHours'](arg1);
}

export function SetMinutes(arg1) {
  return window['go']['backend']['Backend']['SetMinutes'](arg1);
}

export function TimerActive() {
  return window['go']['backend']['Backend']['TimerActive']();
}

export function ToggleTimer() {
  return window['go']['backend']['Backend']['ToggleTimer']();
}
