// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Hours():Promise<number>;

export function Minutes():Promise<number>;

export function RestartTimer():Promise<void>;

export function SetTimerDuration(arg1:number,arg2:number):Promise<void>;

export function TimerActive():Promise<boolean>;

export function ToggleTimer():Promise<void>;
